// examples/solid-ts/src/main.tsx
import { WalletProvider } from '@txnlab/use-wallet-solid'
/* @refresh reload */
import { render } from 'solid-js/web'
import { App } from './App'
import { walletManager } from './walletManager'

render(
  () => (
    <WalletProvider manager={walletManager}>
      <App />
    </WalletProvider>
  ),
  document.getElementById('root')!
)

// examples/react-ts/src/main.tsx
import { WalletProvider } from '@txnlab/use-wallet-react'
import React from 'react'
import ReactDOM from 'react-dom/client'
import { App } from './App'
import { walletManager } from './walletManager'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <WalletProvider manager={walletManager}>
      <App />
    </WalletProvider>
  </React.StrictMode>
)
